from constants.COMMAND import HELP, ATTENDANCE

COMMAND_IDENTIFY = "!"

# 전체 Command 리스트
COMMAND_LIST = [HELP.HELP_COMMAND_LIST, ATTENDANCE.ATTENDANCE_COMMAND_LIST]
COMMAND_REG_LIST = [HELP.HELP_COMMAND_REGEX,
                    ATTENDANCE.ATTENDANCE_COMMAND_REGEX]
