from constants.COMMAND import HELP, ATTENDANCE

COMMAND_IDENTIFY = "!"

# 전체 Command 리스트
COMMAND_LIST = [HELP.COMMAND_LIST, ATTENDANCE.COMMAND_LIST]
COMMAND_REG_LIST = [HELP.COMMAND_REGEX, ATTENDANCE.COMMAND_REGEX]
