from constants.COMMAND import HELP, ATTENDANCE

# 전체 Command 리스트
COMMAND_LIST = [HELP.COMMAND_LIST, ATTENDANCE.COMMAND_LIST]
COMMAND_IDENTIFIER_LIST = [
    HELP.COMMAND_IDENTIFIER, ATTENDANCE.COMMAND_IDENTIFIER]

ERROR = "error"
